name: MSPM33 Zephyr Build Automation Workflow

on:
  push:
  pull_request:

jobs:
  mspm33_build_all:
    runs-on: ubuntu-latest

    steps:
      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt install --no-install-recommends git cmake ninja-build gperf \
          ccache dfu-util device-tree-compiler wget python3-dev python3-venv python3-tk \
          xz-utils file make gcc gcc-multilib g++-multilib libsdl2-dev libmagic1

      - name: Check versions
        run: |
          cmake --version
          python3 --version
          dtc --version

      - name: Create virtual environment
        run: |
          python3 -m venv ~/zephyrproject/.venv

      - name: Activate virtual environment and install west
        run: |
          source ~/zephyrproject/.venv/bin/activate
          pip install --upgrade pip
          pip install west

      - name: Get the Zephyr source code
        run: |
          source ~/zephyrproject/.venv/bin/activate
          # For push events, use github.ref_name; for pull_request events, use github.head_ref
          BRANCH_NAME="${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}"
          echo "Using branch: $BRANCH_NAME"
          west init -m ${{ github.server_url }}/${{ github.repository }} --mr $BRANCH_NAME ~/zephyrproject
          cd ~/zephyrproject
          west update

      - name: Export a Zephyr CMake package
        run: |
          source ~/zephyrproject/.venv/bin/activate
          cd ~/zephyrproject
          west zephyr-export

      - name: Install Zephyr dependencies
        run: |
          source ~/zephyrproject/.venv/bin/activate
          cd ~/zephyrproject
          ~/zephyrproject/.venv/bin/python -m pip install -r ~/zephyrproject/zephyr/scripts/requirements.txt
          west packages pip --install

      - name: Install Zephyr SDK
        run: |
          source ~/zephyrproject/.venv/bin/activate
          cd ~/zephyrproject/zephyr
          west sdk install --toolchain=arm-zephyr-eabi

      - name: Build Blinky example
        run: |
          source ~/zephyrproject/.venv/bin/activate
          cd ~/zephyrproject/zephyr
          source ~/zephyrproject/zephyr/zephyr-env.sh
          west build -p always -b lp_mspm33c321a samples/basic/blinky

      - name: Build Counter Alarm example
        run: |
          source ~/zephyrproject/.venv/bin/activate
          cd ~/zephyrproject/zephyr
          source ~/zephyrproject/zephyr/zephyr-env.sh
          west build -p always -b lp_mspm33c321a samples/drivers/counter/alarm

      - name: Build UART Basic API Test
        run: |
          source ~/zephyrproject/.venv/bin/activate
          cd ~/zephyrproject/zephyr
          source ~/zephyrproject/zephyr/zephyr-env.sh
          west build -p always -b lp_mspm33c321a tests/drivers/uart/uart_basic_api

      - name: Build UART Interrupt API Test
        run: |
          source ~/zephyrproject/.venv/bin/activate
          cd ~/zephyrproject/zephyr
          source ~/zephyrproject/zephyr/zephyr-env.sh
          west build -p always -b lp_mspm33c321a tests/drivers/uart/uart_interrupt_api

      - name: Build Console Line Splitting Test
        run: |
          source ~/zephyrproject/.venv/bin/activate
          cd ~/zephyrproject/zephyr
          source ~/zephyrproject/zephyr/zephyr-env.sh
          west build -p always -b lp_mspm33c321a tests/drivers/console/line_splitting

      - name: Build UART Echo Bot Sample
        run: |
          source ~/zephyrproject/.venv/bin/activate
          cd ~/zephyrproject/zephyr
          source ~/zephyrproject/zephyr/zephyr-env.sh
          west build -p always -b lp_mspm33c321a samples/drivers/uart/echo_bot

      - name: Build SPI Loopback Test
        run: |
          source ~/zephyrproject/.venv/bin/activate
          cd ~/zephyrproject/zephyr
          source ~/zephyrproject/zephyr/zephyr-env.sh
          west build -p always -b lp_mspm33c321a tests/drivers/spi/spi_loopback

      - name: Build SPI DT Spec Test
        run: |
          source ~/zephyrproject/.venv/bin/activate
          cd ~/zephyrproject/zephyr
          source ~/zephyrproject/zephyr/zephyr-env.sh
          west build -p always -b lp_mspm33c321a tests/drivers/spi/dt_spec

      - name: Build Counter Basic API Test
        run: |
          source ~/zephyrproject/.venv/bin/activate
          cd ~/zephyrproject/zephyr
          source ~/zephyrproject/zephyr/zephyr-env.sh
          west build -p always -b lp_mspm33c321a tests/drivers/counter/counter_basic_api
